//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weather.Website.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy.
        /// </summary>
        public static string CloudyType_Cloudy {
            get {
                return ResourceManager.GetString("CloudyType_Cloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair.
        /// </summary>
        public static string CloudyType_Fair {
            get {
                return ResourceManager.GetString("CloudyType_Fair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainlyCloudy.
        /// </summary>
        public static string CloudyType_MainlyCloudy {
            get {
                return ResourceManager.GetString("CloudyType_MainlyCloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcast.
        /// </summary>
        public static string CloudyType_Overcast {
            get {
                return ResourceManager.GetString("CloudyType_Overcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartlyCloudy.
        /// </summary>
        public static string CloudyType_PartlyCloudy {
            get {
                return ResourceManager.GetString("CloudyType_PartlyCloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Precipitation_None {
            get {
                return ResourceManager.GetString("Precipitation_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        public static string Precipitation_Rain {
            get {
                return ResourceManager.GetString("Precipitation_Rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleet.
        /// </summary>
        public static string Precipitation_Sleet {
            get {
                return ResourceManager.GetString("Precipitation_Sleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string Precipitation_Snow {
            get {
                return ResourceManager.GetString("Precipitation_Snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        public static string StrengthPrecipitation_Heavy {
            get {
                return ResourceManager.GetString("StrengthPrecipitation_Heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string StrengthPrecipitation_Light {
            get {
                return ResourceManager.GetString("StrengthPrecipitation_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        public static string TimeOfDay_Evening {
            get {
                return ResourceManager.GetString("TimeOfDay_Evening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Midday.
        /// </summary>
        public static string TimeOfDay_Midday {
            get {
                return ResourceManager.GetString("TimeOfDay_Midday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        public static string TimeOfDay_Morning {
            get {
                return ResourceManager.GetString("TimeOfDay_Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string TimeOfDay_Night {
            get {
                return ResourceManager.GetString("TimeOfDay_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air temp.
        /// </summary>
        public static string WeatherData_AirTemp {
            get {
                return ResourceManager.GetString("WeatherData_AirTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance precipitation.
        /// </summary>
        public static string WeatherData_ChancePrecipitation {
            get {
                return ResourceManager.GetString("WeatherData_ChancePrecipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudy.
        /// </summary>
        public static string WeatherData_Cloudy {
            get {
                return ResourceManager.GetString("WeatherData_Cloudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog.
        /// </summary>
        public static string WeatherData_Fog {
            get {
                return ResourceManager.GetString("WeatherData_Fog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string WeatherData_Humidity {
            get {
                return ResourceManager.GetString("WeatherData_Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precipitation.
        /// </summary>
        public static string WeatherData_Precipitation {
            get {
                return ResourceManager.GetString("WeatherData_Precipitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string WeatherData_Pressure {
            get {
                return ResourceManager.GetString("WeatherData_Pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real feel.
        /// </summary>
        public static string WeatherData_RealFeel {
            get {
                return ResourceManager.GetString("WeatherData_RealFeel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderstorm.
        /// </summary>
        public static string WeatherData_Thunderstorm {
            get {
                return ResourceManager.GetString("WeatherData_Thunderstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of day.
        /// </summary>
        public static string WeatherData_TimeOfDay {
            get {
                return ResourceManager.GetString("WeatherData_TimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind direction.
        /// </summary>
        public static string WeatherData_WindDirection {
            get {
                return ResourceManager.GetString("WeatherData_WindDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed.
        /// </summary>
        public static string WeatherData_WindSpeed {
            get {
                return ResourceManager.GetString("WeatherData_WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string WindDirection_Calm {
            get {
                return ResourceManager.GetString("WindDirection_Calm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string WindDirection_East {
            get {
                return ResourceManager.GetString("WindDirection_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string WindDirection_North {
            get {
                return ResourceManager.GetString("WindDirection_North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        public static string WindDirection_NorthEast {
            get {
                return ResourceManager.GetString("WindDirection_NorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        public static string WindDirection_NorthWest {
            get {
                return ResourceManager.GetString("WindDirection_NorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string WindDirection_South {
            get {
                return ResourceManager.GetString("WindDirection_South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        public static string WindDirection_SouthEast {
            get {
                return ResourceManager.GetString("WindDirection_SouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        public static string WindDirection_SouthWest {
            get {
                return ResourceManager.GetString("WindDirection_SouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string WindDirection_West {
            get {
                return ResourceManager.GetString("WindDirection_West", resourceCulture);
            }
        }
    }
}
