// <auto-generated />
namespace Weather.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TableNames3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableNames3));
        
        string IMigrationMetadata.Id
        {
            get { return "201502272327556_TableNames3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
